
import {UnitType} from "unit-measure"

/**
 * Similer to the nameMapUnit object of unit-measure, but tailored for kitchen usage
 * This names the recognized units.
 * To use: Scan first case-sensitive and then again case-insensitive if no match found first time.
 * Unlike NameMapUnit there are some case-dependent matches here. (e.g. T vs. t)
 */
const matchableUnits = [
    ["packages", UnitType.Count],
    ["package", UnitType.Count],
    ["packets", UnitType.Count],
    ["packet", UnitType.Count],
    ["pkg", UnitType.Count],
    ["pkt", UnitType.Count],
    ["pack", UnitType.Count],
    ["boxes", UnitType.Count],
    ["box", UnitType.Count],
    ["cans", UnitType.Count],
    ["can", UnitType.Count],
    ["bags", UnitType.Count],
    ["bag", UnitType.Count],
    ["pouches", UnitType.Count],
    ["pouch", UnitType.Count],
    ["envelopes", UnitType.Count],
    ["envelope", UnitType.Count],
    ["jars", UnitType.Count],
    ["jar", UnitType.Count],
    ["bottles", UnitType.Count],
    ["bottle", UnitType.Count],
    // ["", UnitType.Count],
    ["each", UnitType.Count],
    ["dozen", UnitType.Dozen],
    ["doz", UnitType.Dozen],
    ["brace", UnitType.Brace],
    ["pair", UnitType.Pair],
    ["pr", UnitType.Pair],
    ["score", UnitType.Score],
    // ["", UnitType.Count],
    // ["", UnitType.Count],
    // ["", UnitType.Count],
    ['microliters', UnitType.Microliter],
    ['microliter', UnitType.Microliter],
    ['ul', UnitType.Microliter],
    ['µl', UnitType.Microliter],
    ['milliliters', UnitType.Milliliter],
    ['milliliter', UnitType.Milliliter],
    ['ml', UnitType.Milliliter],
    ['centiliters', UnitType.Centiliter],
    ['centiliter', UnitType.Centiliter],
    ['cl', UnitType.Centiliter],
    ['cc', UnitType.Centiliter],
    ['deciliters', UnitType.Deciliter],
    ['deciliter', UnitType.Deciliter],
    ['dl', UnitType.Deciliter],
    ['liters', UnitType.Liter],
    ['liter', UnitType.Liter],
    ['l', UnitType.Liter],
    ['fluid ounces', UnitType.FluidOunce],
    ['fluid ounce', UnitType.FluidOunce],
    ['fl. ounces', UnitType.FluidOunce],
    ['fl.ounces', UnitType.FluidOunce],
    ['fl.ounce', UnitType.FluidOunce],
    ['fl. ounce', UnitType.FluidOunce],
    ['fl oz', UnitType.FluidOunce],
    ['fl. oz', UnitType.FluidOunce],
    ['floz', UnitType.FluidOunce],
    ['fl.oz', UnitType.FluidOunce],
    ['pints', UnitType.Pint],
    ['pint', UnitType.Pint],
    ['pt', UnitType.Pint],
    ['quarts', UnitType.Quart],
    ['quart', UnitType.Quart],
    ['qt', UnitType.Quart],
    ['gallons', UnitType.Gallon],
    ['gallon', UnitType.Gallon],
    ['gal', UnitType.Gallon],
    ['teaspoons',UnitType.Teaspoon],
    ['teaspoon',UnitType.Teaspoon],
    ['tsps', UnitType.Teaspoon],
    ['tsp', UnitType.Teaspoon],
    ['t', UnitType.Teaspoon],
    ['tablespoon',UnitType.Tablespoon],
    ['tbsp', UnitType.Tablespoon],
    ['tb',UnitType.Tablespoon],
    ['T',UnitType.Tablespoon],
    ['cups',UnitType.Cup],
    ['cup',UnitType.Cup],
    ['c',UnitType.Cup],
    ['drops',UnitType.Drop],
    ['drop',UnitType.Drop],
    ['drips',UnitType.Drop],
    ['drip',UnitType.Drop],
    ['drp', UnitType.Drop],
    // 'dr', UnitType.Drop], // collides with Dram.
    ['pinch',UnitType.Pinch],
    ['pch', UnitType.Pinch],
    ['dash',UnitType.Dash],
    ['dsh', UnitType.Dash],
    ['cubicmeter', UnitType.CubicMeter],
    ['m3', UnitType.CubicMeter],
    ['cm3', UnitType.CubicCentimeter],
    ['cubicfoot', UnitType.CubicFoot],
    ['ft3', UnitType.CubicFoot],
    ['cft', UnitType.CubicFoot],
    ['cf', UnitType.CubicFoot],
    ['cubicinch', UnitType.CubicInch],
    ['in3', UnitType.CubicInch],
    ['ci', UnitType.CubicInch],
    ['cin', UnitType.CubicInch],

    /* Mass */
    ['grams', UnitType.Gram],
    ['gram', UnitType.Gram],
    ['g', UnitType.Gram],
    ['microgram', UnitType.Microgram],
    ['mcg',UnitType.Microgram],
    ['ug',UnitType.Microgram],
    ['µg',UnitType.Microgram],
    ['milligrams',UnitType.Milligram],
    ['milligram',UnitType.Milligram],
    ['mgs',UnitType.Milligram],
    ['mg',UnitType.Milligram],
    ['kilograms',UnitType.Kilogram],
    ['kilogram',UnitType.Kilogram],
    ['kgs',UnitType.Kilogram],
    ['kg',UnitType.Kilogram],
    ['ounces', UnitType.Ounce],
    ['ounce', UnitType.Ounce],
    ['ozs', UnitType.Ounce],
    ['oz', UnitType.Ounce],
    ['lbs', UnitType.Pound],
    ['lb', UnitType.Pound],
    ['pounds', UnitType.Pound],
    ['pound', UnitType.Pound],
    ['stone', UnitType.Stone],
    ['st', UnitType.Stone],
    ['grain',UnitType.Grain],
    ['gr',UnitType.Grain],
    ['dram',UnitType.Dram],
    ['dr',UnitType.Dram],
    ['troy ounce',UnitType.TroyOunce],
    ['troyounce',UnitType.TroyOunce],
    ['oz t',UnitType.TroyOunce],
    ['ozt',UnitType.TroyOunce],
    ['troy pound',UnitType.TroyPound],
    ['troypound',UnitType.TroyPound],
    ['lb t',UnitType.TroyPound],
    ['lbt',UnitType.TroyPound],
    ['pennyweight',UnitType.Pennyweight],
    ['dwt',UnitType.Pennyweight],
    ['pwt',UnitType.Pennyweight],
    ['pw',UnitType.Pennyweight],
]

export default matchableUnits